version: '2'
services:
    gestionmotor-app:
        image: gestionmotor
        external_links:
            - gestionmotor-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gestionmotor?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    gestionmotor-mysql:
        extends:
            file: mysql.yml
            service: gestionmotor-mysql
